import sounddevice
import soundfile
import multiprocessing
import queue
import tempfile
import logging
import subprocess
import audfprint
import sys

logging.basicConfig(level=logging.INFO)

SAMPLERATE = 44100  # Hertz
DURATION = 3.0  # seconds

lookup = [
    'processed_faded_debussy00000.wav.wav.wav',
    'processed_faded_debussy00001.wav.wav.wav',
    'processed_faded_debussy00002.wav.wav.wav',
    'processed_faded_debussy00003.wav.wav.wav',
    'processed_faded_debussy00004.wav.wav.wav',
    'processed_faded_debussy00005.wav.wav.wav',
    'processed_faded_debussy00006.wav.wav.wav',
    'processed_faded_debussy00007.wav.wav.wav',
    'processed_faded_debussy00008.wav.wav.wav',
    'processed_faded_debussy00009.wav.wav.wav',
    'processed_faded_debussy00010.wav.wav.wav',
    'processed_faded_debussy00011.wav.wav.wav',
    'processed_faded_debussy00012.wav.wav.wav',
    'processed_faded_debussy00013.wav.wav.wav',
    'processed_faded_debussy00014.wav.wav.wav',
    'processed_faded_debussy00015.wav.wav.wav',
    'processed_faded_debussy00016.wav.wav.wav',
    'processed_faded_debussy00017.wav.wav.wav',
    'processed_faded_debussy00018.wav.wav.wav',
    'processed_faded_debussy00019.wav.wav.wav',
    'processed_faded_debussy00020.wav.wav.wav',
    'processed_faded_debussy00021.wav.wav.wav',
    'processed_faded_debussy00022.wav.wav.wav',
    'processed_faded_debussy00023.wav.wav.wav',
    'processed_faded_debussy00024.wav.wav.wav',
    'processed_faded_debussy00025.wav.wav.wav',
    'processed_faded_debussy00026.wav.wav.wav',
    'processed_faded_debussy00027.wav.wav.wav',
    'processed_faded_debussy00028.wav.wav.wav',
    'processed_faded_debussy00029.wav.wav.wav',
    'processed_faded_debussy00030.wav.wav.wav',
    'processed_faded_debussy00031.wav.wav.wav',
    'processed_faded_debussy00032.wav.wav.wav',
    'processed_faded_debussy00033.wav.wav.wav',
    'processed_faded_debussy00034.wav.wav.wav',
    'processed_faded_debussy00035.wav.wav.wav',
    'processed_faded_debussy00036.wav.wav.wav',
    'processed_faded_debussy00037.wav.wav.wav',
    'processed_faded_debussy00038.wav.wav.wav',
    'processed_faded_debussy00039.wav.wav.wav',
    'processed_faded_debussy00040.wav.wav.wav',
    'processed_faded_debussy00041.wav.wav.wav',
    'processed_faded_debussy00042.wav.wav.wav',
    'processed_faded_debussy00043.wav.wav.wav',
    'processed_faded_debussy00044.wav.wav.wav',
    'processed_faded_debussy00045.wav.wav.wav',
    'processed_faded_debussy00046.wav.wav.wav',
    'processed_faded_debussy00047.wav.wav.wav',
    'processed_faded_debussy00048.wav.wav.wav',
    'processed_faded_debussy00050.wav.wav.wav',
    'processed_faded_debussy00051.wav.wav.wav',
    'processed_faded_debussy00052.wav.wav.wav',
    'processed_faded_debussy00053.wav.wav.wav',
    'processed_faded_debussy00054.wav.wav.wav',
    'processed_faded_debussy00055.wav.wav.wav',
    'processed_faded_debussy00056.wav.wav.wav',
    'processed_faded_debussy00057.wav.wav.wav',
    'processed_faded_debussy00058.wav.wav.wav',
    'processed_faded_debussy00059.wav.wav.wav',
    'processed_faded_debussy00060.wav.wav.wav',
    'processed_faded_debussy00061.wav.wav.wav',
    'processed_faded_debussy00062.wav.wav.wav',
    'processed_faded_debussy00063.wav.wav.wav',
    'processed_faded_debussy00064.wav.wav.wav',
    'processed_faded_debussy00065.wav.wav.wav',
    'processed_faded_debussy00066.wav.wav.wav',
    'processed_faded_debussy00067.wav.wav.wav',
    'processed_faded_debussy00068.wav.wav.wav',
    'processed_faded_debussy00069.wav.wav.wav',
    'processed_faded_debussy00070.wav.wav.wav',
    'processed_faded_debussy00071.wav.wav.wav',
    'processed_faded_debussy00072.wav.wav.wav',
    'processed_faded_debussy00073.wav.wav.wav',
    'processed_faded_debussy00074.wav.wav.wav',
    'processed_faded_debussy00075.wav.wav.wav',
    'processed_faded_debussy00076.wav.wav.wav',
    'processed_faded_debussy00077.wav.wav.wav',
    'processed_faded_debussy00078.wav.wav.wav',
    'processed_faded_debussy00079.wav.wav.wav',
    'processed_faded_debussy00080.wav.wav.wav',
    'processed_faded_debussy00081.wav.wav.wav',
    'processed_faded_debussy00082.wav.wav.wav',
    'processed_faded_debussy00083.wav.wav.wav',
    'processed_faded_debussy00084.wav.wav.wav',
    'processed_faded_debussy00085.wav.wav.wav',
    'processed_faded_debussy00086.wav.wav.wav',
    'processed_faded_debussy00087.wav.wav.wav',
    'processed_faded_debussy00088.wav.wav.wav',
    'processed_faded_debussy00089.wav.wav.wav',
    'processed_faded_debussy00090.wav.wav.wav',
    'processed_faded_debussy00091.wav.wav.wav',
    'processed_faded_debussy00092.wav.wav.wav',
    'processed_faded_debussy00093.wav.wav.wav',
    'processed_faded_debussy00094.wav.wav.wav',
    'processed_faded_debussy00095.wav.wav.wav',
    'processed_faded_debussy00096.wav.wav.wav',
    'processed_faded_debussy00097.wav.wav.wav',
    'processed_faded_debussy00098.wav.wav.wav',
    'processed_faded_debussy00099.wav.wav.wav',
    'processed_faded_debussy00100.wav.wav.wav',
    'processed_faded_debussy00101.wav.wav.wav',
    'processed_faded_debussy00102.wav.wav.wav',
    'processed_faded_debussy00103.wav.wav.wav',
    'processed_faded_debussy00104.wav.wav.wav',
    'processed_faded_debussy00105.wav.wav.wav',
    'processed_faded_debussy00106.wav.wav.wav',
    'processed_faded_debussy00107.wav.wav.wav',
    'processed_faded_debussy00108.wav.wav.wav',
    'processed_faded_debussy00109.wav.wav.wav',
    'processed_faded_debussy00110.wav.wav.wav',
    'processed_faded_debussy00111.wav.wav.wav',
    'processed_faded_debussy00112.wav.wav.wav',
    'processed_faded_debussy00113.wav.wav.wav',
    'processed_faded_debussy00114.wav.wav.wav',
    'processed_faded_debussy00115.wav.wav.wav',
    'processed_faded_debussy00116.wav.wav.wav',
    'processed_faded_debussy00117.wav.wav.wav',
    'processed_faded_debussy00118.wav.wav.wav',
    'processed_faded_debussy00119.wav.wav.wav',
    'processed_faded_debussy00120.wav.wav.wav',
    'processed_faded_debussy00121.wav.wav.wav',
    'processed_faded_debussy00122.wav.wav.wav',
    'processed_faded_debussy00123.wav.wav.wav',
    'processed_faded_debussy00124.wav.wav.wav',
    'processed_faded_debussy00125.wav.wav.wav',
    'processed_faded_debussy00126.wav.wav.wav',
    'processed_faded_debussy00127.wav.wav.wav',
    'processed_faded_debussy00128.wav.wav.wav',
    'processed_faded_debussy00129.wav.wav.wav',
    'processed_faded_debussy00130.wav.wav.wav',
    'processed_faded_debussy00131.wav.wav.wav',
    'processed_faded_debussy00132.wav.wav.wav',
    'processed_faded_debussy00133.wav.wav.wav',
    'processed_faded_debussy00134.wav.wav.wav',
    'processed_faded_debussy00135.wav.wav.wav',
    'processed_faded_debussy00136.wav.wav.wav',
    'processed_faded_debussy00137.wav.wav.wav',
    'processed_faded_debussy00138.wav.wav.wav',
    'processed_faded_debussy00139.wav.wav.wav',
    'processed_faded_debussy00140.wav.wav.wav',
    'processed_faded_debussy00141.wav.wav.wav',
    'processed_faded_debussy00142.wav.wav.wav',
    'processed_faded_debussy00143.wav.wav.wav',
    'processed_faded_debussy00144.wav.wav.wav',
    'processed_faded_debussy00145.wav.wav.wav',
    'processed_faded_debussy00146.wav.wav.wav',
    'processed_faded_debussy00147.wav.wav.wav',
    'processed_faded_debussy00148.wav.wav.wav',
    'processed_faded_debussy00149.wav.wav.wav',
    'processed_faded_debussy00150.wav.wav.wav',
    'processed_faded_debussy00151.wav.wav.wav',
    'processed_faded_debussy00152.wav.wav.wav',
    'processed_faded_debussy00153.wav.wav.wav',
    'processed_faded_debussy00154.wav.wav.wav',
    'processed_faded_debussy00155.wav.wav.wav',
    'processed_faded_debussy00156.wav.wav.wav',
    'processed_faded_debussy00157.wav.wav.wav',
    'processed_faded_debussy00158.wav.wav.wav',
    'processed_faded_debussy00159.wav.wav.wav',
    'processed_faded_debussy00160.wav.wav.wav',
    'processed_faded_debussy00161.wav.wav.wav',
    'processed_faded_debussy00162.wav.wav.wav',
    'processed_faded_debussy00163.wav.wav.wav',
    'processed_faded_debussy00164.wav.wav.wav',
    'processed_faded_debussy00165.wav.wav.wav',
    'processed_faded_debussy00166.wav.wav.wav',
    'processed_faded_debussy00167.wav.wav.wav',
    'processed_faded_debussy00168.wav.wav.wav',
    'processed_faded_debussy00169.wav.wav.wav',
    'processed_faded_debussy00170.wav.wav.wav',
    'processed_faded_debussy00171.wav.wav.wav',
    'processed_faded_debussy00172.wav.wav.wav',
    'processed_faded_debussy00173.wav.wav.wav',
    'processed_faded_debussy00174.wav.wav.wav',
    'processed_faded_debussy00175.wav.wav.wav',
    'processed_faded_debussy00176.wav.wav.wav',
    'processed_faded_debussy00177.wav.wav.wav',
    'processed_faded_debussy00178.wav.wav.wav',
    'processed_faded_debussy00179.wav.wav.wav',
    'processed_faded_debussy00180.wav.wav.wav',
    'processed_faded_debussy00181.wav.wav.wav',
    'processed_faded_debussy00182.wav.wav.wav',
    'processed_faded_debussy00183.wav.wav.wav',
    'processed_faded_debussy00184.wav.wav.wav',
    'processed_faded_debussy00185.wav.wav.wav',
    'processed_faded_debussy00186.wav.wav.wav',
    'processed_faded_debussy00187.wav.wav.wav',
    'processed_faded_debussy00188.wav.wav.wav',
    'processed_faded_debussy00189.wav.wav.wav',
    'processed_faded_debussy00190.wav.wav.wav',
    'processed_faded_debussy00191.wav.wav.wav',
    'processed_faded_debussy00192.wav.wav.wav',
    'processed_faded_debussy00193.wav.wav.wav',
    'processed_faded_debussy00195.wav.wav.wav',
    'processed_faded_debussy00196.wav.wav.wav',
    'processed_faded_debussy00197.wav.wav.wav',
    'processed_faded_debussy00198.wav.wav.wav',
    'processed_faded_debussy00199.wav.wav.wav',
    'processed_faded_debussy00200.wav.wav.wav',
    'processed_faded_debussy00201.wav.wav.wav',
    'processed_faded_debussy00202.wav.wav.wav',
    'processed_faded_debussy00203.wav.wav.wav',
    'processed_faded_debussy00204.wav.wav.wav',
    'processed_faded_debussy00205.wav.wav.wav',
    'processed_faded_debussy00206.wav.wav.wav',
    'processed_faded_debussy00207.wav.wav.wav',
    'processed_faded_debussy00208.wav.wav.wav',
    'processed_faded_debussy00209.wav.wav.wav',
    'processed_faded_debussy00210.wav.wav.wav',
    'processed_faded_debussy00211.wav.wav.wav',
    'processed_faded_debussy00212.wav.wav.wav',
    'processed_faded_debussy00213.wav.wav.wav',
    'processed_faded_debussy00214.wav.wav.wav',
    'processed_faded_debussy00216.wav.wav.wav',
    'processed_faded_debussy00217.wav.wav.wav',
    'processed_faded_debussy00218.wav.wav.wav',
    'processed_faded_debussy00219.wav.wav.wav',
    'processed_faded_debussy00220.wav.wav.wav',
    'processed_faded_debussy00221.wav.wav.wav',
    'processed_faded_debussy00222.wav.wav.wav',
    'processed_faded_debussy00223.wav.wav.wav',
    'processed_faded_debussy00224.wav.wav.wav',
    'processed_faded_debussy00225.wav.wav.wav',
    'processed_faded_debussy00226.wav.wav.wav',
    'processed_faded_debussy00227.wav.wav.wav',
    'processed_faded_debussy00228.wav.wav.wav',
    'processed_faded_debussy00229.wav.wav.wav',
    'processed_faded_debussy00230.wav.wav.wav',
    'processed_faded_debussy00231.wav.wav.wav',
    'processed_faded_debussy00232.wav.wav.wav',
    'processed_faded_debussy00233.wav.wav.wav',
    'processed_faded_debussy00234.wav.wav.wav',
    'processed_faded_debussy00235.wav.wav.wav',
    'processed_faded_debussy00236.wav.wav.wav',
    'processed_faded_debussy00237.wav.wav.wav',
    'processed_faded_debussy00238.wav.wav.wav',
    'processed_faded_debussy00239.wav.wav.wav',
    'processed_faded_debussy00240.wav.wav.wav',
    'processed_faded_debussy00241.wav.wav.wav',
    'processed_faded_debussy00242.wav.wav.wav',
    'processed_faded_debussy00243.wav.wav.wav',
    'processed_faded_debussy00244.wav.wav.wav',
    'processed_faded_debussy00245.wav.wav.wav',
    'processed_faded_debussy00246.wav.wav.wav',
    'processed_faded_debussy00247.wav.wav.wav',
    'processed_faded_debussy00247.wav.wav.wav',
    'processed_faded_debussy00247.wav.wav.wav',
    'processed_faded_debussy00247.wav.wav.wav',
    'processed_faded_debussy00248.wav.wav.wav',
    'processed_faded_debussy00248.wav.wav.wav',
    'processed_faded_debussy00248.wav.wav.wav',
    'processed_faded_debussy00248.wav.wav.wav',
    'processed_faded_debussy00249.wav.wav.wav',
    'processed_faded_debussy00249.wav.wav.wav',
    'processed_faded_debussy00249.wav.wav.wav',
    'processed_faded_debussy00249.wav.wav.wav',
    'processed_faded_debussy00250.wav.wav.wav',
    'processed_faded_debussy00250.wav.wav.wav',
    'processed_faded_debussy00250.wav.wav.wav',
    'processed_faded_debussy00250.wav.wav.wav',
    'processed_faded_debussy00251.wav.wav.wav',
    'processed_faded_debussy00251.wav.wav.wav',
    'processed_faded_debussy00251.wav.wav.wav',
    'processed_faded_debussy00251.wav.wav.wav',
    'processed_faded_debussy00252.wav.wav.wav',
    'processed_faded_debussy00252.wav.wav.wav',
    'processed_faded_debussy00252.wav.wav.wav',
    'processed_faded_debussy00252.wav.wav.wav',
    'processed_faded_debussy00253.wav.wav.wav',
    'processed_faded_debussy00253.wav.wav.wav',
    'processed_faded_debussy00253.wav.wav.wav',
    'processed_faded_debussy00253.wav.wav.wav',
    'processed_faded_debussy00254.wav.wav.wav',
    'processed_faded_debussy00254.wav.wav.wav',
    'processed_faded_debussy00254.wav.wav.wav',
    'processed_faded_debussy00254.wav.wav.wav',
    'processed_faded_debussy00255.wav.wav.wav',
    'processed_faded_debussy00255.wav.wav.wav',
    'processed_faded_debussy00255.wav.wav.wav',
    'processed_faded_debussy00255.wav.wav.wav',
    'processed_faded_debussy00256.wav.wav.wav',
    'processed_faded_debussy00256.wav.wav.wav',
    'processed_faded_debussy00256.wav.wav.wav',
    'processed_faded_debussy00256.wav.wav.wav',
    'processed_faded_debussy00257.wav.wav.wav',
    'processed_faded_debussy00257.wav.wav.wav',
    'processed_faded_debussy00257.wav.wav.wav',
    'processed_faded_debussy00257.wav.wav.wav',
    'processed_faded_debussy00258.wav.wav.wav',
    'processed_faded_debussy00258.wav.wav.wav',
    'processed_faded_debussy00258.wav.wav.wav',
    'processed_faded_debussy00258.wav.wav.wav',
    'processed_faded_debussy00259.wav.wav.wav',
    'processed_faded_debussy00259.wav.wav.wav',
    'processed_faded_debussy00259.wav.wav.wav',
    'processed_faded_debussy00259.wav.wav.wav',
    'processed_faded_debussy00260.wav.wav.wav',
    'processed_faded_debussy00260.wav.wav.wav',
    'processed_faded_debussy00260.wav.wav.wav',
    'processed_faded_debussy00260.wav.wav.wav',
    'processed_faded_debussy00261.wav.wav.wav',
    'processed_faded_debussy00261.wav.wav.wav',
    'processed_faded_debussy00261.wav.wav.wav',
    'processed_faded_debussy00261.wav.wav.wav',
    'processed_faded_debussy00262.wav.wav.wav',
    'processed_faded_debussy00262.wav.wav.wav',
    'processed_faded_debussy00262.wav.wav.wav',
    'processed_faded_debussy00262.wav.wav.wav',
    'processed_faded_debussy00263.wav.wav.wav',
    'processed_faded_debussy00263.wav.wav.wav',
    'processed_faded_debussy00263.wav.wav.wav',
    'processed_faded_debussy00263.wav.wav.wav',
    'processed_faded_debussy00264.wav.wav.wav',
    'processed_faded_debussy00264.wav.wav.wav',
    'processed_faded_debussy00264.wav.wav.wav',
    'processed_faded_debussy00264.wav.wav.wav',
    'processed_faded_debussy00265.wav.wav.wav',
    'processed_faded_debussy00265.wav.wav.wav',
    'processed_faded_debussy00265.wav.wav.wav',
    'processed_faded_debussy00265.wav.wav.wav',
    'processed_faded_debussy00266.wav.wav.wav',
    'processed_faded_debussy00266.wav.wav.wav',
    'processed_faded_debussy00266.wav.wav.wav',
    'processed_faded_debussy00266.wav.wav.wav',
    'processed_faded_debussy00267.wav.wav.wav',
    'processed_faded_debussy00267.wav.wav.wav',
    'processed_faded_debussy00267.wav.wav.wav',
    'processed_faded_debussy00267.wav.wav.wav',
    'processed_faded_debussy00268.wav.wav.wav',
    'processed_faded_debussy00268.wav.wav.wav',
    'processed_faded_debussy00268.wav.wav.wav',
    'processed_faded_debussy00268.wav.wav.wav',
    'processed_faded_debussy00269.wav.wav.wav',
    'processed_faded_debussy00269.wav.wav.wav',
    'processed_faded_debussy00269.wav.wav.wav',
    'processed_faded_debussy00269.wav.wav.wav',
    'processed_faded_debussy00270.wav.wav.wav',
    'processed_faded_debussy00270.wav.wav.wav',
    'processed_faded_debussy00270.wav.wav.wav',
    'processed_faded_debussy00270.wav.wav.wav',
    'processed_faded_debussy00271.wav.wav.wav',
    'processed_faded_debussy00271.wav.wav.wav',
    'processed_faded_debussy00271.wav.wav.wav',
    'processed_faded_debussy00271.wav.wav.wav',
    'processed_faded_debussy00272.wav.wav.wav',
    'processed_faded_debussy00272.wav.wav.wav',
    'processed_faded_debussy00272.wav.wav.wav',
    'processed_faded_debussy00272.wav.wav.wav',
    'processed_faded_debussy00273.wav.wav.wav',
    'processed_faded_debussy00273.wav.wav.wav',
    'processed_faded_debussy00273.wav.wav.wav',
    'processed_faded_debussy00273.wav.wav.wav',
    'processed_faded_debussy00274.wav.wav.wav',
    'processed_faded_debussy00274.wav.wav.wav',
    'processed_faded_debussy00274.wav.wav.wav',
    'processed_faded_debussy00274.wav.wav.wav',
    'processed_faded_debussy00275.wav.wav.wav',
    'processed_faded_debussy00275.wav.wav.wav',
    'processed_faded_debussy00275.wav.wav.wav',
    'processed_faded_debussy00275.wav.wav.wav',
    'processed_faded_debussy00276.wav.wav.wav',
    'processed_faded_debussy00276.wav.wav.wav',
    'processed_faded_debussy00276.wav.wav.wav',
    'processed_faded_debussy00276.wav.wav.wav',
    'processed_faded_debussy00277.wav.wav.wav',
    'processed_faded_debussy00277.wav.wav.wav',
    'processed_faded_debussy00277.wav.wav.wav',
    'processed_faded_debussy00277.wav.wav.wav',
    'processed_faded_debussy00278.wav.wav.wav',
    'processed_faded_debussy00278.wav.wav.wav',
    'processed_faded_debussy00278.wav.wav.wav',
    'processed_faded_debussy00278.wav.wav.wav',
    'processed_faded_debussy00279.wav.wav.wav',
    'processed_faded_debussy00279.wav.wav.wav',
    'processed_faded_debussy00279.wav.wav.wav',
    'processed_faded_debussy00279.wav.wav.wav',
    'processed_faded_debussy00280.wav.wav.wav',
    'processed_faded_debussy00280.wav.wav.wav',
    'processed_faded_debussy00280.wav.wav.wav',
    'processed_faded_debussy00280.wav.wav.wav',
    'processed_faded_debussy00281.wav.wav.wav',
    'processed_faded_debussy00281.wav.wav.wav',
    'processed_faded_debussy00281.wav.wav.wav',
    'processed_faded_debussy00281.wav.wav.wav',
    'processed_faded_debussy00282.wav.wav.wav',
    'processed_faded_debussy00282.wav.wav.wav',
    'processed_faded_debussy00282.wav.wav.wav',
    'processed_faded_debussy00282.wav.wav.wav',
    'processed_faded_debussy00283.wav.wav.wav',
    'processed_faded_debussy00283.wav.wav.wav',
    'processed_faded_debussy00283.wav.wav.wav',
    'processed_faded_debussy00283.wav.wav.wav',
    'processed_faded_debussy00284.wav.wav.wav',
    'processed_faded_debussy00284.wav.wav.wav',
    'processed_faded_debussy00284.wav.wav.wav',
    'processed_faded_debussy00284.wav.wav.wav',
    'processed_faded_debussy00285.wav.wav.wav',
    'processed_faded_debussy00285.wav.wav.wav',
    'processed_faded_debussy00285.wav.wav.wav',
    'processed_faded_debussy00285.wav.wav.wav',
    'processed_faded_debussy00286.wav.wav.wav',
    'processed_faded_debussy00286.wav.wav.wav',
    'processed_faded_debussy00286.wav.wav.wav',
    'processed_faded_debussy00286.wav.wav.wav'
]
last_byte = 255
def process_file(filename):
    global last_byte 
    logging.info(f"processing {filename}")
    fingerprint, fingerprint_filename = audfprint.fingerprint_filename(filename, 'words.pklz')
    logging.info(f"processed {filename}: found hash:{fingerprint}, filename of hash: {fingerprint_filename}")
    if fingerprint_filename:
        try:
            word = fingerprint_filename.rsplit('/', 1)[1]
            byte = lookup.index(word)
            last_byte = byte
            sys.stdout.buffer.write(bytes([byte]))
            sys.stdout.buffer.flush()
            logging.info(f"wrote byte: {int(byte)}")
        except:
            logging.exception("error")
    elif sys.argv[1] == 'zerofill':
        logging.exception("zerofilled")
        sys.stdout.buffer.write(bytes([last_byte]))
        sys.stdout.buffer.flush()




def consumer(q, exit):
    while not exit.is_set():
        try:
            mydata = q.get(timeout=0.1)
            with tempfile.NamedTemporaryFile(suffix='.wav') as file:
                filename = file.name
                soundfile.write(filename, mydata, SAMPLERATE)
                process_file(file.name)
        except:
            logging.debug("no items to process")
    logging.warning("consumer exiting")

def main():
    if sys.argv[1] == 'zerofill':
        sys.stdout.buffer.write(bytes([last_byte]))
        sys.stdout.buffer.flush()
    q = multiprocessing.Queue()
    processes = []
    exit_event = multiprocessing.Event()
    for target in [consumer]:
        dead_queue = queue.Queue()
        process = multiprocessing.Process(target=target, args=(q, exit_event,))
        process.daemon = True
        process.start()
        processes.append(process)
    try:
        while True:
            mydata = sounddevice.rec(
                int(SAMPLERATE * DURATION), 
                samplerate=SAMPLERATE, 
                channels=2, 
                blocking=True
            )
            q.put(mydata, block=True)
            logging.info(f"producer put data in queue")
    except:
        logging.exception("interupted")
        pass

    exit_event.set()
    for process in processes:
        process.join()
        logging.info("process died")
    
    logging.info("no more processes, exiting")

if __name__ == "__main__":
    main()